{% set version = "1.9.4" %}

package:
  name: argcomplete
  version: {{ version }}

source:
  fn: argcomplete-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/a/argcomplete/argcomplete-{{ version }}.tar.gz
  md5: 06c8a54ffaa6bfc9006314498742ec8843601206a3b94212f82657673662ecf1

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - argcomplete

about:
  home: https://github.com/kislyuk/argcomplete
  license: Apache 2.0
  summary: 'Bash tab completion for argparse'
  license_family: Apache
  license_file: LICENSE.rst
  doc_url: https://argcomplete.readthedocs.io
  dev_url: https://github.com/kislyuk/argcomplete

extra:
  recipe-maintainers:
    - asmeurer
