{% set version = "1.11.0" %}

package:
  name: argcomplete
  version: {{ version }}

source:
  fn: argcomplete-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/a/argcomplete/argcomplete-{{ version }}.tar.gz
  md5: 238329371c6cc8259f9fa4f64633e648

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python
    
requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
test:
  imports:
    - argcomplete

about:
  home: https://github.com/kislyuk/argcomplete
  license: Apache 2.0
  summary: 'Bash tab completion for argparse'
  license_family: Apache
  license_file: LICENSE.rst
  doc_url: https://argcomplete.readthedocs.io
  dev_url: https://github.com/kislyuk/argcomplete

extra:
  recipe-maintainers:
    - asmeurer
    - xylar
