travis:
  secure:
    BINSTAR_TOKEN: SpW5AjQJqY0TzGKCM6NHvdG5rGROUumiavydtOopWhXoX5DZ1jW7Tq5G+3ljzfh8Lx3v7X/rBDiZHpsFbDREaKuMXBoVrDH3Kqtiu1yj3sz1C7Mf2dslvDrxPC46wK2DBCU7FfTo6KjgQrUMwRWD5ohy/wJGMgZ99BvWpCDJng+Jr6ihkxy7+uIEyE7qQtWjryTvCq+1lkYbQTO+wt9gUs0mjV+T27Bg3FHR6lMm322PYQM30BIhwnYBHxDL0PFxxvsFOiBRZ0GFj6416aE4lX3eEn5J9uxTtcay3LIjto/t/RIBw7LFiVPptFKt8egRSx8H/z5s0ezzXgTmkhoexZMEo87lGVFcwmgidO98NIfhC0kBxuHWj1gUEZupfv6igMUn90U9aIRS4w4yQsN5YC8tMW5YGzJqh5veXwfJ5GFgk5mtlsVqfd6pHEIdqYdAM4qOw+QAYqEpo9ykcS5cCP21DiYlGVq7W9ZHfDnnzIv+ZFGaoISzt72Mq0YBVFQNYaps8Ww+boxYVpkmPxv89uf2ltkj0XyKeg0SqLcawhAwzcbnMDJB2kYnBCej+GiNM05A+i9rv7dr1yO5jjmG/B9UmGJK6NLihFv9Fc8G+x2v/mrVbU/uzasE4xKNDr835gxzcwoVfx9pwe5JjgRQp2m8oTrbGdQWmpcGQsnaAKk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
